-- Schéma PostgreSQL aligné avec les entités JPA
-- NOTE: Ce fichier est un aide-mémoire et n'est pas exécuté par Spring Boot.
-- Hibernate (ddl-auto) crée/ajuste les tables lors du démarrage.

-- =========================
-- 1) Référentiels
-- =========================
CREATE TABLE IF NOT EXISTS type_demande (
  code_type VARCHAR(20) PRIMARY KEY,
  libelle VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS statut_demande (
  code_statut VARCHAR(20) PRIMARY KEY,
  libelle VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS statut_creneau (
  code_statut VARCHAR(20) PRIMARY KEY,
  libelle VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS statut_rendez_vous (
  code_statut VARCHAR(20) PRIMARY KEY,
  libelle VARCHAR(100) NOT NULL
);

-- =========================
-- 2) Tables principales
-- =========================
CREATE TABLE IF NOT EXISTS client (
  id_client INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR(100) NOT NULL,
  prenom VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  mot_de_passe VARCHAR(255) NOT NULL,
  email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  email_verified_at TIMESTAMP NULL,
  immatriculation VARCHAR(255) NOT NULL,
  vehicule_marque VARCHAR(100),
  vehicule_modele VARCHAR(100),
  telephone VARCHAR(20) NOT NULL,
  adresse_ligne1 VARCHAR(255),
  adresse_ligne2 VARCHAR(255),
  adresse_code_postal VARCHAR(20),
  adresse_ville VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS administrateur (
  id_admin INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  mot_de_passe VARCHAR(255) NOT NULL,
  nom VARCHAR(100),
  prenom VARCHAR(100),
  email VARCHAR(150) UNIQUE
);

CREATE TABLE IF NOT EXISTS service (
  id_service INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle VARCHAR(100) NOT NULL,
  description TEXT,
  icon TEXT,
  prix_unitaire NUMERIC(10,2) NOT NULL,
  quantite_max INTEGER NOT NULL,
  archived BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS creneau (
  id_creneau INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_debut TIMESTAMP NOT NULL,
  date_fin TIMESTAMP NOT NULL,
  code_statut VARCHAR(20) NOT NULL,
  CONSTRAINT fk_creneau_statut FOREIGN KEY (code_statut)
    REFERENCES statut_creneau(code_statut)
);

CREATE TABLE IF NOT EXISTS demande (
  id_demande INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_client INTEGER NOT NULL,
  date_demande TIMESTAMP NOT NULL,
  code_type VARCHAR(20) NOT NULL,
  code_statut VARCHAR(20) NOT NULL,
  CONSTRAINT fk_demande_client FOREIGN KEY (id_client)
    REFERENCES client(id_client),
  CONSTRAINT fk_demande_type FOREIGN KEY (code_type)
    REFERENCES type_demande(code_type),
  CONSTRAINT fk_demande_statut FOREIGN KEY (code_statut)
    REFERENCES statut_demande(code_statut)
);

CREATE TABLE IF NOT EXISTS demande_service (
  id_demande INTEGER NOT NULL,
  id_service INTEGER NOT NULL,
  quantite INTEGER NOT NULL,
  libelle_service VARCHAR(100) NOT NULL,
  description_service TEXT,
  prix_unitaire_service NUMERIC(10,2) NOT NULL,
  PRIMARY KEY (id_demande, id_service),
  CONSTRAINT fk_demande_service_demande FOREIGN KEY (id_demande)
    REFERENCES demande(id_demande),
  CONSTRAINT fk_demande_service_service FOREIGN KEY (id_service)
    REFERENCES service(id_service)
);

CREATE TABLE IF NOT EXISTS devis (
  id_devis INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_demande INTEGER NOT NULL UNIQUE,
  date_devis TIMESTAMP NOT NULL,
  montant_total NUMERIC(12,2) NOT NULL,
  montant_main_oeuvre NUMERIC(12,2),
  montant_pieces NUMERIC(12,2),
  CONSTRAINT fk_devis_demande FOREIGN KEY (id_demande)
    REFERENCES demande(id_demande)
);

CREATE TABLE IF NOT EXISTS rendez_vous (
  id_rdv INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_demande INTEGER NOT NULL UNIQUE,
  id_admin INTEGER NOT NULL,
  id_creneau INTEGER NOT NULL UNIQUE,
  code_statut VARCHAR(20) NOT NULL,
  commentaire TEXT,
  CONSTRAINT fk_rdv_demande FOREIGN KEY (id_demande)
    REFERENCES demande(id_demande),
  CONSTRAINT fk_rdv_admin FOREIGN KEY (id_admin)
    REFERENCES administrateur(id_admin),
  CONSTRAINT fk_rdv_creneau FOREIGN KEY (id_creneau)
    REFERENCES creneau(id_creneau),
  CONSTRAINT fk_rdv_statut FOREIGN KEY (code_statut)
    REFERENCES statut_rendez_vous(code_statut)
);

CREATE TABLE IF NOT EXISTS disponibilite (
  id_admin INTEGER NOT NULL,
  id_creneau INTEGER NOT NULL,
  PRIMARY KEY (id_admin, id_creneau),
  CONSTRAINT fk_dispo_admin FOREIGN KEY (id_admin)
    REFERENCES administrateur(id_admin),
  CONSTRAINT fk_dispo_creneau FOREIGN KEY (id_creneau)
    REFERENCES creneau(id_creneau)
);

CREATE TABLE IF NOT EXISTS demande_document (
  id_document BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_demande INTEGER NOT NULL,
  nom_fichier VARCHAR(255) NOT NULL,
  url_private VARCHAR(512),
  type_contenu VARCHAR(100),
  taille_octets BIGINT,
  visible_client BOOLEAN NOT NULL DEFAULT TRUE,
  cree_par VARCHAR(150),
  cree_par_role VARCHAR(30),
  cree_le TIMESTAMP NOT NULL,
  CONSTRAINT fk_demande_document_demande FOREIGN KEY (id_demande)
    REFERENCES demande(id_demande)
);

CREATE TABLE IF NOT EXISTS demande_timeline (
  id_timeline BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_demande INTEGER NOT NULL,
  type_evenement VARCHAR(30) NOT NULL,
  cree_le TIMESTAMP NOT NULL,
  cree_par VARCHAR(150),
  cree_par_role VARCHAR(30),
  visible_client BOOLEAN NOT NULL DEFAULT TRUE,
  statut_code VARCHAR(20),
  statut_libelle VARCHAR(100),
  commentaire VARCHAR(1000),
  montant_valide NUMERIC(12,2),
  document_id BIGINT,
  document_nom VARCHAR(255),
  document_url VARCHAR(512),
  rendezvous_id INTEGER,
  rendezvous_statut_code VARCHAR(20),
  rendezvous_statut_libelle VARCHAR(100),
  rendezvous_date_debut TIMESTAMP,
  rendezvous_date_fin TIMESTAMP,
  CONSTRAINT fk_demande_timeline_demande FOREIGN KEY (id_demande)
    REFERENCES demande(id_demande)
);

CREATE TABLE IF NOT EXISTS promotion (
  id_promotion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_admin INTEGER NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  valid_from TIMESTAMP NOT NULL,
  valid_to TIMESTAMP NOT NULL,
  description TEXT NOT NULL,
  CONSTRAINT fk_promotion_admin FOREIGN KEY (id_admin)
    REFERENCES administrateur(id_admin)
);

CREATE TABLE IF NOT EXISTS email_verification_token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_client INTEGER NOT NULL,
  token VARCHAR(200) NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  consumed_at TIMESTAMP,
  CONSTRAINT fk_evt_client FOREIGN KEY (id_client)
    REFERENCES client(id_client)
);

CREATE TABLE IF NOT EXISTS password_reset_token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_client INTEGER NOT NULL,
  token VARCHAR(200) NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP,
  CONSTRAINT fk_prt_client FOREIGN KEY (id_client)
    REFERENCES client(id_client)
);

CREATE INDEX IF NOT EXISTS idx_evt_token ON email_verification_token(token);
CREATE INDEX IF NOT EXISTS idx_evt_client ON email_verification_token(id_client);
CREATE INDEX IF NOT EXISTS idx_prt_token ON password_reset_token(token);
CREATE INDEX IF NOT EXISTS idx_prt_client ON password_reset_token(id_client);
