name: CI/CD Backend & Frontend

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      TAG: ''

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Run tests
        run: mvn test -B

      - name: Build JAR
        run: mvn clean package -DskipTests -B

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine image tag
        id: tag
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" == "main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=dev-${GITHUB_SHA::8}" >> $GITHUB_ENV
          fi

      # --- Backend ---
      - name: Build & push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./jlh
          file: ./jlh/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USER }}/jlh-autopam-backend:${{ env.TAG }}

      # --- Frontend ---
      - name: Build & push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USER }}/jlh-autopam-frontend:${{ env.TAG }}

  deploy-production:
    needs: build-and-push
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Déployer en local (prod)
        run: |
          docker-compose -f docker-compose.prod.yml pull backend
          docker-compose -f docker-compose.prod.yml pull frontend
          docker-compose -f docker-compose.prod.yml up -d
