# .github/workflows/ci-cd-backend.yml
name: CI/CD Backend

# Permissions nécessaires pour push sur Docker Hub (packages) et checkout
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
      - dev

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run tests
        run: mvn test -B

      - name: Build JAR
        run: mvn clean package -DskipTests -B

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker image tag
        id: set-tag
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" == "main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=dev-${GITHUB_SHA::8}" >> $GITHUB_ENV
          fi

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USER }}/jlh-autopam-backend:${{ env.TAG }}

      - name: Logout from Docker Hub
        run: docker logout docker.io

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: build-and-push
    runs-on: self-hosted
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull & run prod container
        run: |
          docker-compose -f docker-compose.prod.yml pull backend
          docker-compose -f docker-compose.prod.yml up -d backend
