name: CI/CD Backend

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/jlh-autopam-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run tests
        run: mvn test -B

      - name: Build JAR
        run: mvn clean package -DskipTests -B

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine image tag
        id: tag
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=dev-${GITHUB_SHA::8}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}

  deploy-production:
    needs: build-and-push
    runs-on: self-hosted
    if: github.ref_name == 'main'
    defaults:
      run:
        working-directory: /chemin/vers/votre/jlh/appli  # si nécessaire

    steps:
      - uses: actions/checkout@v3

      - name: Déployer en local
        run: |
          docker-compose -f docker-compose.prod.yml pull jlh
          docker-compose -f docker-compose.prod.yml up -d jlh