name: CI/CD Backend

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  # 1) build-and-push sur ubuntu-latest
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Run tests
        run: mvn test -B

      - name: Build JAR
        run: mvn clean package -DskipTests -B

      - name: Debug DOCKERHUB_USER
        run: echo "DOCKERHUB_USER is '$DOCKERHUB_USER'"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine image tag
        id: set-tag
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" == "main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=dev-${GITHUB_SHA::8}" >> $GITHUB_ENV
          fi
      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{  secrets.DOCKERHUB_USERNAME }}/jlh-autopam-backend:${{ env.TAG }}

  # 2) deploy-production sur le self-hosted (qui n'a pas Maven, mais uniquement Docker)
  deploy-production:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3

      - name: Debug runner environment
        run: |
          echo "==> Current dir = $(pwd)"
          echo "==> Listing files:"
          ls -al .
          echo "==> Docker version:" 
          docker version
          echo "==> Docker info:"
          docker info
          echo "==> Docker-compose version:"
          docker-compose version

      - name: Pull & run prod container
        run: |
          docker-compose -f docker-compose.prod.yml pull backend
          docker-compose -f docker-compose.prod.yml up -d backend